baseURL = "https://blog.spbennett.org/"
languageCode = "en-us"
title = "Home"
theme = "nuevo-massively"

[params]
  Author = "Steven Bennett"

[params.settings]
  googleanalytics = "UA-121227360-1"

[languages]
[languages.en]
  languageName = "English"

[[params.navlinks]]
  name = "Home"
  url = ""

[[params.navlinks]]
  name = "About"
  url = "about/"

[[params.navlinks]]
  name = "Get in touch"
  url = "contact/"